import { initializeApp } from "firebase/app";
import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { getFirestore, doc, getDoc, setDoc } from "firebase/firestore";

// Generated by firestore on project creation
const firebaseConfig = {
	apiKey: "AIzaSyA4sHkOwFx2rAjzgVgfxkktqU5fcUN_pU8",
	authDomain: "apex-store-db.firebaseapp.com",
	projectId: "apex-store-db",
	storageBucket: "apex-store-db.appspot.com",
	messagingSenderId: "407675975299",
	appId: "1:407675975299:web:80ff16de9b10ef42150db6",
};

///////////////////////////////////////////////////////////////////////////////////////////
// FIREBASE CONFIG
///////////////////////////////////////////////////////////////////////////////////////////
// Connect this web app with the firebase cloud using the config
const firebaseApp = initializeApp(firebaseConfig);
// get the authentication object
export const auth = getAuth();
// Create a new authentication provider to access our firebase auth
const provider = new GoogleAuthProvider();
// Set what to show when the authenticator appears
provider.setCustomParameters({
	prompt: "select_account",
});
// Create a popup method which will use the auth and provider
export const signInWithGooglePopup = () => signInWithPopup(auth, provider);

///////////////////////////////////////////////////////////////////////////////////////////
// FIRESTORE CONFIG
///////////////////////////////////////////////////////////////////////////////////////////
// Get reference to out database (firestore) on firebase
export const db = getFirestore(firebaseApp);

///////////////////////////////////////////////////////////////////////////////////////////
// FIRESTORE METHODS
///////////////////////////////////////////////////////////////////////////////////////////
export const createUserDocumentFromAuth = async (userAuth) => {
	// Get reference to given uid document from 'users' collections from our firestore db
	const userDocRef = doc(db, "users", userAuth.uid);

	// Get the documet using the reference
	const userDoc = await getDoc(userDocRef);
	// Check whether given document exists in the collection
	const doesExist = userDoc.exists();

	// if document doesnt exist, set the new document
	if (!doesExist) {
		const { displayName, email } = userAuth;
		const createdAt = new Date();

		try {
			// Set the given data as document to the collection users
			await setDoc(userDocRef, {
				displayName,
				email,
				createdAt,
			});
		} catch (err) {
			console.log(
				`Error encountered while creating the account for ${displayName}. Error: ${err.message}`
			);
		}
	}

	return userDocRef;
};
